[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
authors = ["TheBlackSheep3"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
